label: "hw1_prob2_coarse"
mesh:
  nodes:
    - {id: 1, x: 0.0}
    - {id: 2, x: 90.0}
    - {id: 3, x: 180.0}
    - {id: 4, x: 270.0}
    - {id: 5, x: 360.0}
  elements:
    - {id: 1, node_i: 1, node_j: 2, type: beam, material: beam_mat}
    - {id: 2, node_i: 2, node_j: 3, type: beam, material: beam_mat}
    - {id: 3, node_i: 3, node_j: 4, type: beam, material: beam_mat}
    - {id: 4, node_i: 4, node_j: 5, type: beam, material: beam_mat}
materials:
  beam_mat: {E: 1.0e6, A: 1.0, I: 1.0}
boundary_conditions:
  - {node_id: 1, type: fixed_all}
loads:
  nodal:
    - {node_id: 5, type: point_force_y, magnitude: -10.0}
  distributed:
    - {element_id: 1, type: distributed_y, w_i: 0.025, w_j: 0.025}
    - {element_id: 2, type: distributed_y, w_i: 0.025, w_j: 0.025}
    - {element_id: 3, type: distributed_y, w_i: 0.025, w_j: 0.025}
    - {element_id: 4, type: distributed_y, w_i: 0.025, w_j: 0.025}
