label: "hw1_prob3_fine"
mesh:
  nodes:
    - {id: 1, x: 0.0}
    - {id: 2, x: 40.4}
    - {id: 3, x: 80.8}
    - {id: 4, x: 121.2}
    - {id: 5, x: 161.6}
    - {id: 6, x: 202.0}
    - {id: 7, x: 242.4}
  elements:
    - {id: 1, node_i: 1, node_j: 2, type: beam, material: wing}
    - {id: 2, node_i: 2, node_j: 3, type: beam, material: wing}
    - {id: 3, node_i: 3, node_j: 4, type: beam, material: wing}
    - {id: 4, node_i: 4, node_j: 5, type: beam, material: wing}
    - {id: 5, node_i: 5, node_j: 6, type: beam, material: wing}
    - {id: 6, node_i: 6, node_j: 7, type: beam, material: wing}
materials:
  wing: {E: 1.0e6, A: 1.0, I: 1.0}
boundary_conditions:
  - {node_id: 1, type: fixed_all}
  - {node_id: 3, type: roller}
loads:
  nodal: []
  distributed:
    - {element_id: 1, type: distributed_linear, w_i: 0.065635, w_j: 0.064718}
    - {element_id: 2, type: distributed_linear, w_i: 0.064718, w_j: 0.061878}
    - {element_id: 3, type: distributed_linear, w_i: 0.061878, w_j: 0.056839}
    - {element_id: 4, type: distributed_linear, w_i: 0.056839, w_j: 0.048909}
    - {element_id: 5, type: distributed_linear, w_i: 0.048909, w_j: 0.036284}
    - {element_id: 6, type: distributed_linear, w_i: 0.036284, w_j: 0.0}
