label: "hw1_prob4_fine"
mesh:
  nodes:
    - {id: 1, x: 0.0}
    - {id: 2, x: 60.09}
    - {id: 3, x: 120.18}
    - {id: 4, x: 180.27}
    - {id: 5, x: 240.36}
    - {id: 6, x: 30.045}
    - {id: 7, x: 90.135}
    - {id: 8, x: 150.225}
    - {id: 9, x: 210.315}
  elements:
    - {id: 1, node_i: 1, node_j: 6, type: beam, material: beam_mat}
    - {id: 2, node_i: 6, node_j: 2, type: beam, material: beam_mat}
    - {id: 3, node_i: 2, node_j: 7, type: beam, material: beam_mat}
    - {id: 4, node_i: 7, node_j: 3, type: beam, material: beam_mat}
    - {id: 5, node_i: 3, node_j: 8, type: beam, material: beam_mat}
    - {id: 6, node_i: 8, node_j: 4, type: beam, material: beam_mat}
    - {id: 7, node_i: 4, node_j: 9, type: beam, material: beam_mat}
    - {id: 8, node_i: 9, node_j: 5, type: beam, material: beam_mat}
materials:
  beam_mat: {E: 1.0e6, A: 1.0, I: 1.0}
boundary_conditions:
  - {node_id: 2, type: roller}
  - {node_id: 4, type: roller}
loads:
  nodal:
    - {node_id: 3, type: point_moment, magnitude: 100.0}
  distributed: []
